### PR TITLE
fix background / text color in FF

### PR DESCRIPTION
**Pull request by d47081**
on dark theme environment I have contrast issue in FF, when background color not defined as white. that's small fix just for default white theme even better to have adaptive theme for nightly users.

image

### CODE REVIEW

**Comment by d47081** [comment]
After fixes above, suppose that website should looks like in Chrome on my OS

image

**Comment by stephank** [comment]
Thanks for pointing this out! I decided to go a slightly different route. I recently discovered you can do:

```
:root {
  color-scheme: light dark;
}
```

And get dark system colors! So I deployed 0a72e1a65e51fd25362c88276cd2e5504c8479f2 and that should work for you too, hopefully?

**Comment by d47081** [comment]
wow, I didn't know this trick!

looks much better, thank you

image

**Comment by d47081** [comment]
Just found that FF in light mode now shows gray background with `color-scheme` implementation :/

image

That's browser issue, but anyway, for info

ps. dark mode works well
pps. tested on linux platform only, maybe just my FF build or my own settings... 

image

so fixed for myself with "Use system colors" settings, but not sure about others, theirs defaults

**Pull request closed without merging**
